### ISSUE TITLE
Restructure text in notebook based docs isn't rendering right

### ISSUE THREAD

**Issue by ivirshup** [PMBio/mudata#5]
Looks like something is going wrong in the conversion of notebooks to pages in the docs:

<img width="719" alt="image" src="https://user-images.githubusercontent.com/8238804/145615382-aef75491-f1b4-49fa-8af0-964011160398.png">

There are a number of links with this problem in page from `quickstart_mudata.ipynb`

**Comment by gtca** [comment]
Thanks, apparently Markdown's backticks in link names are not properly handled by nbsphinx, at least automatically.
I changed that in eec0ba5, which should fix the rendering issues that I noticed.
Please let me know in case there's more!
