### ISSUE TITLE
CI testing

### ISSUE THREAD

**Issue by ivirshup** [PMBio/mudata#9]
It would be good to get the test suite running on CI.

Is there a strong preference for platforms?

**Comment by gtca** [comment]
There's a `pytest` run already set up: https://github.com/PMBio/mudata/blob/master/.github/workflows/pythonpackage.yml.
Or did you mean something else?

I've now added a hook to run it on PRs too (135a935).

**Comment by ivirshup** [comment]
Great, just only saw linting run on my PR, will merge master
